### ISSUE TITLE
The eraser cause problem on exported image

### ISSUE THREAD

**Issue by lablnet** [lablnet/board#10]
The eraser cause problem on exported image it show backgrounds color 
here below is snapshort
![board10_1_2020, 9_07_18 AM](https://user-images.githubusercontent.com/27757785/94767347-8a613880-03c5-11eb-863f-68b331ebe1f9.png)

Make a fix for that.
Thanks

**Comment by wasim0315** [comment]
I want to do it for Hacktoberfest.

**Comment by lablnet** [comment]
> I want to do it for Hacktoberfest.

assigned

**Comment by wasim0315** [comment]
Could you please elaborate the issue I exported an image but that image had no background.

**Comment by lablnet** [comment]
> Could you please elaborate the issue I exported an image but that image had no background.

Draw someething then control + mouse drag to remove it then export it

**Comment by lablnet** [comment]
@wasim0315  do you have any plan to continue?

**Comment by wasim0315** [comment]
@lablnet  I drawn something and then exported the image but the image was with no background.....I am facing this issue......If the exported image was there, then it can be solved.
By just taking the eraser and using it as a pen with color same as the background color . As you can see it in the image you have uploaded above , you erased with black background color as pen. And in exported image you got the color made by eraser , But there is no background color.

**Comment by lablnet** [comment]
> @lablnet I drawn something and then exported the image but the image was with no background.....I am facing this issue......If the exported image was there, then it can be solved.
> By just taking the eraser and using it as a pen with color same as the background color . As you can see it in the image you have uploaded above , you erased with black background color as pen. And in exported image you got the color made by eraser , But there is no background color.

We have recently added option export with background, then there is no such issue, but when user click export , it basically without background transparent, the we have issue as you said above.

**Comment by karmanya007** [comment]
Is this issue being actively worked upon. If not, I would like to work on this.

**Comment by lablnet** [comment]
> Is this issue being actively worked upon. If not, I would like to work on this.

Thanks, @wasim0315  was not able to work out, if you want to @karmanya007 takee over let me know? but make sure you should work

**Comment by karmanya007** [comment]
Yeah ,I am think of using the [globalCompositeOperation](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation) property to change the compositing operation when drawing/erasing.
How does this sound?

**Comment by lablnet** [comment]
> Yeah ,I am think of using the [globalCompositeOperation](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation) property to change the compositing operation when drawing/erasing.
> How does this sound?

Sounds looks good to me, assigned to you

**Comment by lablnet** [comment]
@karmanya007 no update from you?

**Comment by karmanya007** [comment]
Can't seen to fix the problem. I initially fixed it but broke the normal export functionality. Sorry 😔
