### ISSUE TITLE
refresh PWA cache 

### ISSUE THREAD

**Issue by lablnet** [lablnet/board#9]
When the file change i mean update the PWA and browser did not  update the page because it stored in cache.

So make fix to  refresh cache.

**Comment by yerlantemir** [comment]
Hi, could you assign it to me?

**Comment by lablnet** [comment]
> Hi, could you assign it to me?

Thanks for showing interest assigned

**Comment by yerlantemir** [comment]
@lablnet I couldn't see this bug locally, maybe I missunderstood. Could you provide steps to repeat this bug? Thanks in advance

**Comment by lablnet** [comment]
> @lablnet I couldn't see this bug locally, maybe I missunderstood. Could you provide steps to repeat this bug? Thanks in advance

We have github gh-pages branch when i merge changes to that, and open link then i havve to refresh cache to browser then it will work let me give you example, i merge master into gh-page

i reload page i see
![image](https://user-images.githubusercontent.com/27757785/94767727-b3ce9400-03c6-11eb-8ff5-b1f8e4bc734c.png)

but after pressing ctrl+f5 to refresh cache i see
![image](https://user-images.githubusercontent.com/27757785/94767748-c47f0a00-03c6-11eb-8020-e934bbb6f187.png)


so this is the acthal problem, in mobile specially it cause problem!

**Comment by lablnet** [comment]
> @lablnet I couldn't see this bug locally, maybe I missunderstood. Could you provide steps to repeat this bug? Thanks in advance

Use localhost server you will see this bug then
